/* eslint-disable prettier/prettier */
export * from './catalogues.service';
export * from './carrera.service';
export * from './persona.service';
export * from './catalogo.service';
export * from './portafolio.service';
export * from './tutor_academico.service';
export * from './documento.service';
export * from './detalle-portafolio.service';
export * from './rol.service';
