/* eslint-disable prettier/prettier */
export enum RepositoryEnum {
  CATALOGUE_REPOSITORY = 'CATALOGUE_REPOSITORY',

  USER_REPOSITORY = 'USER_REPOSITORY',

  CARRERA_REPOSITORY = 'CARRERA_REPOSITORY',

  PERSONA_REPOSITORY = 'PERSONA_REPOSITORY',

<<<<<<< HEAD
  EMPRESA_REPOSITORY = 'EMPRESA_REPOSITORY',
  
  ROL_REPOSITORY = 'ROL_REPOSITORY',
=======
  CATALOGO_REPOSITORY = 'CATALOGO_REPOSITORY',

  PORTAFOLIO_REPOSITORY = 'PORTAFOLIO_REPOSITORY',
>>>>>>> f48f4ca9ac4578fa5ea11e47d7737baed1b43a0f

  DETALLE_PORTAFOLIO_REPOSITORY = 'DETALLE_PORTAFOLIO_REPOSITORY',

  DOCUMENTO_REPOSITORY = 'DOCUMENTO_RESPOSITORY',

  TUTOR_ACADEMICO_REPOSITORY = 'TUTOR_ACADEMICO_REPOSITORY',
}
