export enum RepositoryEnum {
  CATALOGUE_REPOSITORY = 'CATALOGUE_REPOSITORY',

  USER_REPOSITORY = 'USER_REPOSITORY',

  CARRERA_REPOSITORY = 'CARRERA_REPOSITORY',

  PERSONA_REPOSITORY = 'PERSONA_REPOSITORY',
}
