/* eslint-disable prettier/prettier */
export * from './catalogues/catalogue.dto';
export * from './catalogues/create-catalogue.dto';
export * from './catalogues/update-catalogue.dto';
export * from './catalogues/filter-catalogue.dto';
export * from './pagination/pagination.dto';
export * from './carrera/create-carrera.dto';
export * from './carrera/update-carrera.dto';
export * from './carrera/filter-carrera.dto';
export * from './persona/create-persona.dto';
export * from './persona/update-persona.dto';
export * from './persona/filter-persona.dto';
export * from './documento/create-documento.dto';
export * from './documento/update-documento.dto';
export * from './detalle-portafolio/create-detalle-portafolio.dto';
export * from './detalle-portafolio/update-detalle-portafolio.dto';